#+language: ru
#+latex_class: extreport
#+latex_class_options: [a4paper,12pt]
#+latex_header: \usepackage{fontspec}
#+latex_header: \usepackage[AUTO]{babel}
#+latex_header: \usepackage{indentfirst}
#+latex_header: \setmainfont{PT Astra Serif}
#+latex_header: \usepackage[margin=1.5cm]{geometry}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[b]{esvect}

#+latex_header: \newtheorem{theorem}{Теорема}[section]
#+latex_header: \newtheorem{lemma}[theorem]{Лемма}
#+latex_header: \newtheorem{property}[theorem]{Свойство}

#+latex_header: \theoremstyle{definition}
#+latex_header: \newtheorem{definition}{Определение}[section]

#+latex_header: \newcommand{\newpar}{$ $\par\nobreak\ignorespaces}
#+latex_header: \renewenvironment{proof}{{\noindent\bfseries Доказательство.}}{\smallskip\newpar \hfill\textit{Что и требовалось доказать.}}

#+latex_header: \usepackage[x11names]{xcolor}
#+latex_header: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = PaleGreen1, linkcolor = black}


* Электрическое поле в вакууме

** Электрический заряд

#+begin_definition
Электрический заряд — физическая величина, определяющая силу создаваемого им электрического взаимодействия. Единица измерения заряда в СИ — Кулон (Кл). Также заряд — это внутреннее свойство элементарных частиц, а также источник и объект действия электромагнитного поля;
#+end_definition

#+begin_definition
Кулон — электрический заряд, проходящий через поперечное сечение проводника при силе тока 1 ампер за 1 секунду.
#+end_definition

Все тела образованы из атомов или молекул, которые, в свою очередь, состоят из ядер и электронов, обладающих электрическим зарядом. Существует два типа зарядов, условно называемых отрицательными (электроны) и положительными (ядра атомов). Силы электрического взаимодействия связывают ядро и электроны в единую систему — атом.

Наименьший по величине электрический заряд (элементарный заряд), экспериментально обнаруженный в природе, — заряд электрона:
\begin{equation*}
    q_e = -e,
    \quad
    e = 1.6 \cdot 10^{-19} \; \text{Кл}.
\end{equation*}

Положительный заряд атомных ядер образован входящими в их состав протонами. Заряд протона положителен и по величине равен заряду электрона \(q_p = +e\). В каждом атоме суммы положительных и отрицательных зарядов равны по абсолютной величине, и поэтому обычно тела оказываются электронейтральными. Однако можно оторвать электроны от одних тел, которые становятся при этом положительно заряженными, и передать их другим телам, которые заряжаются отрицательно. Такие тела являются /макроскопически заряженными/. Электрический заряд любого тела кратен элементарному заряду \(e\), т. е. изменяется дискретно на величину
\begin{equation*}
    \Delta q = \pm Ne,
    \quad
    N \in \mathbb{Z}.
\end{equation*}

Многочисленные эксперименты доказали, что электрический заряд сохраняется:
\begin{equation*}
    \sum_i q_i = \text{const}.
\end{equation*}

Между заряженными телами возникают особые силы, называемые /электрическими силами/.Одноименные заряды отталкиваются, а разноименные — притягиваются.

** Закон Кулона
#+begin_definition
    Точечный электрический заряд — заряженное тело, размер которого много меньше расстояния его возможного действия на другие тела.
#+end_definition

Сформулируем закон Кулона. Пусть имеются две заряженные частицы, причем
- \(q_1\) и \(q_2\) — величина зарядов;
- \(\vv{F_{12}}\) — сила, с которой действует заряд 1 на заряд 2;
- \(\vv{F_{21}}\) — сила, с которой действует заряд 2 на заряд 1;
- \(\vv{r_{12}}\) — вектор, направленный от заряда 1 к заряду 2 и по модулю равный расстоянию между ними (\(r\));
Тогда закон Кулона можно сформулировать следующим образом:

#+begin_definition
    Сила взаимодействия двух неподвижных точечных зарядов в пустоте пропорционально величине каждого из зарядов, обратно пропорциональна квадрату расстояния между ними и направлена по прямой, соединяющей эти заряды
    \begin{equation*}
        \vv{F_{12}} = -\vv{F_{21}},
        \qquad
        \vv{F_{12}} = k \frac{q_1 q_2}{r^2} \frac{\vv{r_{12}}}{r}.
    \end{equation*}
    \begin{center}
        \includegraphics[width=0.5\textwidth]{images/coulomb.png}
    \end{center}
    Закон кулона применим, если в условии данной задачи заряды можно рассматривать как /точечные/.
#+end_definition

Коэффициент пропорциональности \(k\) в СИ равен (здесь \(\varepsilon_0\) – электрическая постоянная):
\begin{equation*}
    k = \frac{1}{4\pi\varepsilon_0} = 9 \cdot 10^9 \; \frac{\text{Н} \cdot \text{м}^2}{\text{Кл}^2},
    \qquad
    \varepsilon_0 = 8.85 \cdot 10^{-12} \; \frac{\text{Кл}^2}{\text{Н} \cdot \text{м}^2},
\end{equation*}
