* TODO Список вопросов
- [X] Какие носители электрического заряда вы знаете?
- [ ] Чем заряженное тело отличается от нейтрального на атомарном уровне?
- [X] Что такое квантованность заряда?
- [X] Укажите основные свойства электрического заряда
- [ ] Как осуществляется взаимодействие между электрическими зарядами?
- [ ] С какой скоростью осуществляется взаимодействие между электрическими зарядами?
- [X] Запишите закон Кулона в векторной форме
- [ ] Что является силовой характеристикой электрического поля?
- [X] Что называется напряжённостью электрического поля?
- [X] Запишите формулу для напряжённости точечного заряда?
- [X] Какой заряд называют пробным?
- [X] Запишите формулу для напряжённости электрического поля, созданной точечным зарядом?
- [ ] Что называют объёмной плотностью заряда, формула и единицы измерения?
- [ ] Что называют поверхностной плотностью заряда, формула и единицы измерения?
- [ ] Что называют линейной плотностью заряда, формула и единицы измерения
- [X] Дайте определение телесного угла
- [ ] Что такое поток однородного векторного поля через плоскую площадку?
- [ ] Как вычислить поток вектора напряжённости электрического поля через замкнутую поверхность?
- [ ] Запишите теорему Гаусса для вектора E в вакууме для системы точечных зарядов и для тела , заряженного с объёмной плотностью ρ.
- [ ] Нарисуйте картину линий напряжённости и эквипотенциальных поверхностей заряженной сферы
- [ ] Нарисуйте картину линий напряжённости и эквипотенциальных поверхностей полого заряженного цилиндра
- [ ] Запишите теорему Гаусса для вектора E в дифференциальной форме.
- [ ] Какие силы называют консервативными?
- [ ] Всегда ли центральные силы являются консервативными?
- [ ] Что называют потенциальной энергией частицы в поле?
- [ ] Как связана работа сил поля с изменением потенциальной энергии частицы в поле?
- [ ] Что называется потенциалом электростатического поля?
- [ ] Что называется потенциальной энергией точечного электрического заряда в электростатическом поле?
- [ ] В чём заключается принцип суперпозиции потенциала?
- [ ] Как связаны между собой сила и потенциальная энергия?
- [ ] Как связаны между собой напряжённость и потенциал?
- [ ] Что называют электрическим диполем?
- [ ] Что называют дипольным моментом?
- [ ] Запишите формулу для напряжённости, создаваемой электрическим диполем
- [ ] Запишите формулу для потенциала, создаваемого электрическим диполем
- [ ] Как определяется потенциальная энергия диполя в электрическом поле?
- [ ] Как вычислить силу, действующую на диполь в электрическом поле?
- [ ] Как вычислить механический момент, действующий на диполь в электрическом поле?
- [ ] Что называют полем поляризации в диэлектрике?
- [ ] Как при поляризации диэлектрика возникают связанные заряды ?
- [ ] Как происходит поляризация полярных диэлектриков?
- [ ] Как происходит поляризация неполярных диэлектриков?
- [ ] Как происходит поляризация ионных кристаллов?
- [ ] Что называют поляризуемостью молекулы, в каких единицах она измеряется?
- [ ] Что называют поляризованностью вещества (формула и единицы измерения) ?
- [ ] Что называют вектором поляризации вещества (формула и единицы измерения) ?
- [ ] Что называют диэлектрической восприимчивостью среды, в каких единицах она измеряется?
- [ ] Что называют диэлектрической проницаемостью среды, в каких единицах она измеряется?
- [ ] Запишите теорему Гаусса для вектора поляризации P в интегральной и дифференциальной формах?
- [ ] Дайте определение вектора электрической индукции. В каких единицах она измеряется?
- [ ] Запишите теорему Гаусса для вектора электрической индукции.
- [ ] Как в однородном изотропном диэлектрике связаны напряжённость электрического поля и вектор электрической индукции?
- [ ] Как связаны диэлектрическая проницаемость среды и диэлектрическая восприимчивость?
- [ ] Чему равна циркуляция электрической напряженности, созданной неподвижными электрическими зарядами?
- [ ] Запишите граничные условия для вектора E на границе раздела диэлектрик диэлектрик
- [ ] Запишите граничные условия для вектора E на границе раздела диэлектрик вакуум.
- [ ] Запишите граничные условия для вектора D на границе раздела диэлектрик диэлектрик
- [ ] Запишите граничные условия для вектора D на границе раздела диэлектрик вакуум.
- [ ] Запишите закон преломления линий вектора E на границе раздела диэлектрик диэлектрик.
- [ ] Запишите закон преломления линий вектора D на границе раздела диэлектрик диэлектрик
- [ ] Какие вещества называют пьезоэлектриками?
- [ ] В чём заключается поперечный пьезоэлектрический эффект?
- [ ] В чём заключается продольный пьезоэлектрический эффект?
- [ ] Опишите прямой и обратный пьезоэлектрические эффекты?
- [ ] Какие вещества называются пироэлектриками?
- [ ] Какие вещества называются сегнетоэлектриками?
- [ ] За счёт чего возникает гистерезис в сегнетоэлектриках?
- [ ] Нарисуйте петлю гистерезиса в сегнетоэлектрике, покажите остаточную поляризацию и коэрцитивную силу.
- [ ] Постройте график зависимости диэлектрической проницаемости в сегнетоэлектрике от приложенного поля
- [ ] Что происходит в сегнетоэлектриках при нагревании выше температуры Кюри?
- [ ] Металлическое тело находится в электрическом поле. Что вы можете сказать о значении потенциала в различных точках этого тела?
- [ ] Как направлены линии напряжённости по отношению к поверхности заряженного проводящего тела. Почему?
- [ ] Запишите уравнение Пуассона и Лапласа
- [ ] В чём заключается метод электрических изображений для металлов?
- [ ] Нарисуйте заряд отображения для точечного заряда вблизи бесконечной проводящей плоскости
- [ ] Что называется электрической емкостью уединённого проводника?
- [ ] Что называют ёмкостью конденсатора?
- [ ] Как вычислить ёмкость последовательно соединённых конденсаторов?
- [ ] Как вычислить ёмкость параллельно соединённых конденсаторов?
- [ ] Выведите формулу для ёмкости плоского конденсатора
- [ ] Выведите формулу для ёмкости сферического конденсатора
- [ ] Выведите формулу для ёмкости на единицу длины цилиндрического конденсатора.
- [ ] Запишите формулу для энергии заряженного конденсатора
- [ ] Конденсатор присоединён к источнику. Его параметры изменяют. За счёт работы каких сил меняется энергия конденсатора?
- [ ] Конденсатор присоединён к источнику. Его параметры изменяют. Как вычислить работу источника тока?
- [ ] Конденсатор присоединён к источнику. Его параметры изменяют. Как вычислить работу сил поля?
- [ ] Вычислите силу притяжения пластин плоского конденсатора
- [ ] Запишите формулу для энергии системы точечных зарядов
- [ ] Как вычислить энергию заряженного уединённого проводника?
- [ ] Выведите формулу для энергии заряженного конденсатора
- [ ] Как вычислить объёмную плотность энергии электрического поля?
- [ ] Что называют силой тока?
- [ ] Как связана сила тока в проводнике со скоростью направленного движения носителей?
- [ ] Что называют электрическим сопротивлением?
- [ ] Запишите формулу для электрического сопротивления цилиндрического проводника
- [ ] Что называют плотностью тока?
- [ ] Запишите формулу для эквивалентного сопротивления при параллельном соединении проводников.
- [ ] Запишите формулу для эквивалентного сопротивления при последовательном соединении проводников
- [ ] Что называется электродвижущей силой источника тока?
- [ ] Какие силы называются сторонними?
- [ ] Чем отличается электродвижущая сила источника тока от разности потенциалов на его электродах?
- [ ] Какое уравнение выражает закон сохранения электрического заряда?
- [ ] Запишите уравнение непрерывности
- [ ] Запишите закон Ома для однородного участка цепи в интегральной и дифференциальной формах
- [ ] Запишите закон Ома для неоднородного участка цепи в интегральной и дифференциальной формах
- [ ] Какая физическая величина называется удельной проводимостью, в каких единицах она измеряется
- [ ] Какая физическая величина называется напряжением на участке цепи?
- [ ] Сформулируйте законы Кирхгофа
- [ ] Получите законы Кирхгофа
- [ ] Вычислите ЭДС и суммарное внутреннее сопротивление источников при последовательном и параллельном соединении одинаковых источников в батарею
- [ ] Выведите формулы для преобразования треугольник- звезда
- [ ] Запишите формулу для мощности тока для однородного участка цепи в интегральной форме
- [ ] Запишите формулу для мощности тока для однородного участка цепи в дифференциальной форме
- [ ] Запишите формулу для мощности тока для неоднородного участка цепи в интегральной форме
- [ ] Запишите формулу для мощности тока для неоднородного участка цепи в дифференциальной форме
- [ ] Выведите соотношение между сопротивлением источника и нагрузки, позволяющее получить максимальную полезную мощность
- [ ] Как можно создать магнитное поле?
- [ ] На какие объекты может действовать магнитное поле?
- [ ] Запишите формулу для индукции магнитного поля, созданного движущейся заряженной частицей
- [ ] Вычислите индукцию магнитного поля в центре кругового витка
- [ ] Вычислите индукцию магнитного поля прямого тока на расстоянии a от него
- [ ] Запишите теорему Гаусса для вектора B
- [ ] Какое уравнение показывает, что линии индукции магнитного поля всегда замкнуты?
- [ ] Запишите закон Био-Савара-Лапласа
- [ ] Запишите теорему о циркуляции вектора магнитной индукции в интегральной форме (в отсутствие магнетиков)
- [ ] Запишите теорему о циркуляции вектора магнитной индукции в дифференциальной форме (в отсутствие магнетиков)
- [ ] Выведите формулу для индукции магнитного поля в нутрии длинного соленоида.
- [ ] Запишите формулу для силы Лоренца
- [ ] Заряженная частица движется по окружности в магнитном поле. Выведите формулу для радиуса окружности
- [ ] Заряженная частица движется по спирали в однородном магнитном поле. Выведите формулу для радиуса и шага винтовой линии
- [ ] Запишите формулу для силы Ампера
- [ ] Как вычислить работу сил магнитного поля при перемещении контура с током?
- [ ] Что называют магнитным моментом контура с током?
- [ ] Как вычислить силу, действующую на контур с током в магнитном поле?
- [ ] Как вычислить механический момент, действующий на контур с током в магнитном поле?
- [ ] Как вычислить потенциальную энергию контура с током в магнитном поле?
- [ ] Как возникают токи намагничивания?
- [ ] Что называют намагниченностью магнетика ? В каких единицах она измеряется?
- [ ] Что называют вектором намагничивания? В каких единицах он измеряется?
- [ ] Запишите теорему о циркуляции вектора намагничивания в интегральной форме
- [ ] Запишите теорему о циркуляции вектора намагничивания в дифференциальной форме
- [ ] Запишите теорему о циркуляции вектора B при наличии магнетика.
- [ ] Что называется напряжённостью магнитного поля? В каких единицах она измеряется?
- [ ] Запишите теорему о циркуляции напряжённости магнитного поля в интегральной и дифференциальной формах .
- [ ] Как связаны намагниченность и напряжённость магнитного поля?
- [ ] Что называют магнитной восприимчивостью среды, в каких единицах она измеряется?
- [ ] Что называют магнитной проницаемостью среды, в каких единицах она измеряется?
- [ ] Как связаны индукция магнитного поля и напряжённость магнитного поля
- [ ] Запишите теорему Гаусса для вектора B при наличии магнетика
- [ ] Выведите граничные условия для векторов B и H на границе магнетиков.
- [ ] Выведите закон преломления линий индукции магнитного поля на границе двух магнетиков
- [ ] Выведите закон преломления линий напряжённости магнитного поля на границе двух магнетиков
- [ ] Какие вещества называются парамагнетиками? Какова их магнитная проницаемость?
- [ ] Какие вещества называются диамагнетиками ? Какова их магнитная проницаемость?
- [ ] Какие вещества называются ферромагнетиками?
- [ ] Что такое доменная структура ферромагнетиков?
- [ ] Изобразите петлю гистерезиса в ферромагнетиках.
- [ ] Как магнитная проницаемость ферромагнетика зависит от внешнего поля?
- [ ] Что такое температура Кюри для ферромагнетиков?
- [ ] Почему при нагревании выше температуры Кюри ферромагнетики теряют свои свойства?
- [ ] Запишите закон электромагнитной индукции Фарадея.
- [ ] Сформулируйте правило Ленца
- [ ] Опишите природу возникновения ЭДС индукции в движущемся проводнике.
- [ ] Опишите природу возникновения ЭДС индукции в неподвижном контуре при изменении магнитного потока через него
- [ ] Какое электрическое поле называется вихревым?
- [ ] Запишите теорему о циркуляции вихревого электрического поля в интегральной и дифференциальной форме.
- [ ] Что называется индуктивностью контура, в каких единицах она измеряется?
- [ ] Получите формулу для индуктивности на 1 метр длины бесконечно длинного соленоида
- [ ] Дайте определение коэффициента взаимной индукции.
- [ ] Два соленоида с током находятся в непосредственной близости друг от друга. Как вычислить их суммарную индуктивность.
- [ ] Запишите формулу для объёмной плотности энергии магнитного поля.
- [ ] Два соленоида с током находятся в непосредственной близости друг от друга. Как вычислить суммарную энергию магнитного поля в них?
- [ ] Дайте определение тока смещения.
- [ ] Приведите простейший пример, доказывающий необходимость введения тока смещения.
- [ ] Что называется плотностью полного тока?
- [ ] Перечислите свойства тока смещения.
- [ ] Приводит ли наличие тока смещения к выделению джоулевой теплоты?
- [ ] Запишите систему уравнений Максвелла в интегральной форме.
- [ ] Запишите систему уравнений Максвелла в дифференциальной форме.
- [ ] Запишите систему уравнений Максвелла в стационарном случае.
- [ ] Как доказать, что изменяющееся во времени электрическое поле порождает магнитное?
- [ ] Как доказать, что изменяющееся во времени магнитное поле порождает электрическое?
- [ ] Каким образом можно создать электрическое поле? Подтвердите уравнениями.
- [ ] Каким образом можно создать магнитное поле? Подтвердите уравнениями.
- [ ] Какими уравнениями надо дополнить систему уравнений Максвелла?
- [ ] Что называется материальными уравнениями?
- [ ] Запишите формулу для объёмной плотности энергии электромагнитного поля.
- [ ] Что называется вектором плотности потока энергии электромагнитного поля?
- [ ] Запишите вектор Умова-Пойнтинга. Что он показывает?
- [ ] Запишите уравнение гармонических колебаний.
- [ ] Что называется фазой колебаний?
- [ ] Что называется начальной фазой колебаний?
- [ ] Запишите зависимость скорости точки, совершающей гармонические колебания от времени.
- [ ] Запишите зависимость ускорения точки, совершающей гармонические колебания от времени.
- [ ] Что называется уравнением гармонического осциллятора.
- [ ] Как определить амплитуду и начальную фазу колебаний, зная координату и скорость точки в начальный момент времени и циклическую частоту колебаний?
- [ ] Запишите уравнение колебаний пружинного маятника.
- [ ] Получите формулу для периода колебаний пружинного маятника.
- [ ] Запишите уравнение колебаний математического маятника.
- [ ] Получите формулу для периода колебаний математического маятника.
- [ ] Запишите уравнение колебаний физического маятника.
- [ ] Получите формулу для периода колебаний физического маятника.
- [ ] Получите формулу для полной энергии гармонического осциллятора.
- [ ] Как период колебаний кинетической энергии гармонического осциллятора соотносится с периодом его колебаний?
- [ ] Покажите, как можно определить амплитуду и фазу суммы колебаний при помощи векторной диаграммы?
- [ ] Всегда ли энергия суммы колебаний равна сумме энергий колебаний?
- [ ] Как результат сложения взаимно перпендикулярных колебаний зависит от сдвига фаз?
- [ ] Запишите уравнение колебаний заряда в колебательном контуре в отсутствие затухания.
- [ ] Выведите формулу для периода колебаний заряда в контуре в отсутствие затухания.
- [ ] Запишите уравнение затухающих механических колебаний.
- [ ] Запишите уравнение затухающих электромагнитных колебаний.
- [ ] Как выглядит решение уравнения затухающих колебаний в случае малого затухания ? (Примеры для механических и электромагнитных колебаний)
- [ ] Как определяется амплитуда затухающих гармонических колебаний в случае малого затухания? (Примеры для механических и электромагнитных колебаний)
- [ ] Как определяется частота затухающих гармонических колебаний в случае малого затухания? (Примеры для механических и электромагнитных колебаний)
- [ ] Что называют коэффициентом затухания ? ( Как он зависит от характеристик колебательной системы?)
- [ ] Что называют временем релаксации для затухающих механических колебаний ? (Как оно зависит от характеристик колебательной системы?)
- [ ] Что называют логарифмическим декрементом затухания? (Примеры для механических и электромагнитных колебаний)
- [ ] Что называют добротностью колебательной системы?(Примеры для механических и электромагнитных колебаний)
- [ ] Запишите уравнение вынужденных механических колебаний.
- [ ] Как определить амплитуду и фазу установившихся вынужденных механических колебаний с помощью векторной диаграммы?.
- [ ] Как выглядит уравнение установившихся вынужденных механических колебаний?
- [ ] Когда при вынужденных механических колебаниях наступает резонанс?
- [ ] При какой частоте вынуждающей силы наступает резонанс в механической колебательной системе?
- [ ] Каков сдвиг фаз между смещением и вынуждающей силой при резонансе в механической колебательной системе?
- [ ] Запишите уравнение вынужденных электромагнитных колебаний.
- [ ] Как определить амплитуду и фазу установившихся вынужденных колебаний тока в контуре с помощью векторной диаграммы?
- [ ] Как выглядит уравнение установившихся вынужденных колебаний заряда конденсатора?
- [ ] Как выглядит уравнение установившихся вынужденных колебаний тока в катушке индуктивности?
- [ ] Когда при вынужденных электромагнитных колебаниях наступает резонанс по току?
- [ ] Когда при вынужденных электромагнитных колебаниях наступает резонанс заряда конденсатора?
- [ ] При какой частоте вынуждающей ЭДС наступает резонанс по току в колебательном контуре?
- [ ] При какой частоте вынуждающей ЭДС наступает резонанс по заряду конденсатора в колебательном контуре?
- [ ] Каков сдвиг фаз между током и вынуждающей ЭДС при резонансе в колебательном контуре?
- [ ] Каков сдвиг фаз между зарядом конденсатора и вынуждающей ЭДС при резонансе в колебательном контуре?
- [ ] Какие волны называют стоячими, а какие бегущими?
- [ ] Что называют волновой поверхностью?
- [ ] Запишите уравнение плоской синусоидальной волны.
- [ ] Запишите уравнение плоской синусоидальной волны через волновой вектор.
- [ ] Запишите уравнение плоской синусоидальной волны в комплексном виде.
- [ ] Запишите уравнение сферической синусоидальной волны.
- [ ] Что называют волновым вектором?
- [ ] Что называют длиной волны?
- [ ] Как амплитуда сферической волны зависит от расстояния до источника?
- [ ] Что называется волновым уравнением? Приведите пример.
- [ ] Что называется фазовой скоростью волны?
- [ ] Запишите волновое уравнение для вектора E.
- [ ] Запишите волновое уравнение для вектора H.
- [ ] Покажите скорость распространения электромагнитных волн в волновом уравнении?
